# 1) n = 100

In [59]:
import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt

In [60]:
n = 100
u = np.random.normal(0,1,n)
d = np.random.normal(0,1,n)

In [61]:
u @ u.T # Хотим получить матрицу, а не число !!!

71.29642611035173

In [62]:
u = u[:, np.newaxis] # Делаем из u - вектор столбец. Чтобы посчитать u @ u.T (должна получиться матрица, а не число)

In [63]:
u.shape

(100, 1)

In [64]:
# Cоберем матрицу А
A = (u @ u.T)/(u.T @ u) + np.diag(d)
np.min(LA.eigvalsh(A)) # минимальное собственное число

-3.096499171622585

In [65]:
sys = LA.eigh(A)
sys[0]

array([-3.09649917e+00, -2.64180890e+00, -1.96324353e+00, -1.72043558e+00,
       -1.58926435e+00, -1.57839393e+00, -1.38915243e+00, -1.38740433e+00,
       -1.37079670e+00, -1.16298023e+00, -1.14635333e+00, -1.13780576e+00,
       -9.97107677e-01, -9.87653175e-01, -9.26594696e-01, -8.82446608e-01,
       -8.64839999e-01, -8.43040389e-01, -8.26924502e-01, -8.02354767e-01,
       -6.93000908e-01, -6.89111690e-01, -6.83782518e-01, -6.77304615e-01,
       -6.53346493e-01, -6.29388106e-01, -6.24187044e-01, -6.11350892e-01,
       -5.82158815e-01, -5.76554180e-01, -5.67702246e-01, -4.36676990e-01,
       -4.32304343e-01, -4.09557878e-01, -3.97477980e-01, -3.34937834e-01,
       -3.24745074e-01, -2.89778779e-01, -2.82662899e-01, -2.70773997e-01,
       -2.51481446e-01, -2.37482425e-01, -2.23584599e-01, -2.14617196e-01,
       -1.90846271e-01, -1.78381956e-01, -1.05130987e-01, -9.71997708e-02,
       -7.16945134e-02, -5.36298307e-02, -2.70130951e-02, -1.97870805e-02,
       -1.30728308e-02,  

In [66]:
sys[1]

array([[ 2.75705948e-03, -9.48710488e-03,  9.98655508e-01, ...,
        -4.50488618e-03,  5.41141359e-04,  4.23922027e-03],
       [-2.83030274e-03,  7.37455832e-03,  9.62854550e-03, ...,
         1.19979552e-02, -1.39388096e-03, -1.08981640e-02],
       [ 1.88734907e-05, -4.75313066e-05, -5.61306531e-05, ...,
        -1.03537139e-04,  1.18423848e-05,  9.25083937e-05],
       ...,
       [ 9.20812414e-04, -2.10204798e-03, -1.97289745e-03, ...,
        -5.45623219e-02,  3.74232547e-03,  2.85875586e-02],
       [ 1.29995766e-03, -3.40891686e-03, -4.54308296e-03, ...,
        -5.28872677e-03,  6.15751757e-04,  4.81489812e-03],
       [ 2.28485008e-03, -5.29075005e-03, -5.11155376e-03, ...,
        -5.45421950e-02,  5.07900527e-03,  3.92633667e-02]])

In [67]:
a = sys[:][:][1]

In [68]:
c =a[:][0]
c # собственный вектор, соответствующий минимальному собственному занчению

array([ 2.75705948e-03, -9.48710488e-03,  9.98655508e-01, -3.00854237e-02,
        7.31142821e-04, -8.06868047e-03,  8.35946447e-04, -2.78577110e-03,
        1.90270514e-02, -1.16291557e-02,  1.16908987e-03, -3.06857175e-04,
       -4.12220765e-04,  5.43680098e-03, -9.59406855e-03, -5.30225787e-03,
        5.94342934e-04,  2.09590011e-03, -3.39995296e-03, -6.05903377e-04,
       -7.04308816e-04, -1.85934468e-03, -1.84227345e-04,  3.57073604e-03,
        9.18582689e-04,  1.04170490e-05,  1.22864255e-03, -4.80478013e-03,
       -1.39071146e-03, -6.80982220e-04,  5.33543817e-03,  1.35213925e-04,
        4.53600688e-04, -1.88423770e-03, -6.91984576e-03,  1.27662389e-03,
        3.18621509e-04,  2.15379610e-04,  5.01460380e-04,  1.17553372e-03,
       -1.01617984e-03, -1.53896718e-04, -1.76402608e-03, -4.42466199e-05,
       -3.54640112e-03,  2.04396990e-03,  1.10275941e-03,  7.92408853e-05,
        4.52778496e-04,  1.10031128e-03, -1.63519423e-04, -5.21423973e-04,
       -6.40139450e-04, -

# 2) n = 10**5

In [70]:
n = 100000
d = np.random.normal(0, 1, (n,1))
u = np.random.normal(0,1, (n,1))
u = u/LA.norm(u)

In [71]:
d_inv = 1/d
mu = 1 + u.T@(d_inv*u)
print(mu)

[[1.04368951]]


In [72]:
####Ищем максимальное собственное число квадрата обратной матрицы
N = 0
x = np.zeros((n,1))
x[0,0] = 1 
h = np.zeros((n,1))
L_prev = 1
for i in range (1000):
    y = d_inv*x - (u.T@(d_inv*x))*(d_inv*u)/mu
    y = d_inv*y - (u.T@(d_inv*y))*(d_inv*u)/mu
    L = float(x.T@y)
    x = y/LA.norm(y)
    L_prev = L 
    if (np.abs(L - L_prev) < 10.**(-3)):
        h=x
        L = L_prev
h=x
print(LA.norm(h))
print(h.T, L)
print('\n')

x = np.zeros((n,1))
x[0,0] = 1
for i in range (100):
    y = d_inv*x - (u.T@(d_inv*x))*(d_inv*u)/mu
    y = d_inv*y - (u.T@(d_inv*y))*(d_inv*u)/mu
    L = float(x.T@y)
    N += 1
    x = y/LA.norm(y)
 
    print("Результат итерации "+f"{N}" +"-" + f"{x.T}" )
    print("Почти собственное число" +"  " + f"{L}")
    print("Невязка  " + f"{LA.norm(x-h).round(8)}")
    print('\n')
   
    if (LA.norm(x-h)<10.**(-8)):
        break

#Lambda = (h.T@C@h)/(h.T@h)
#print(Lambda)

1.0000000000000007
[[ 3.73052565e-06 -4.82831058e-06  1.94837602e-05 ...  1.45894797e-07
  -3.02503463e-06 -1.38728844e-05]] 12453806311.228952


Результат итерации 1-[[ 3.62422956e-05 -9.07921958e-06  3.66348216e-05 ...  2.74331286e-07
  -5.68818870e-06 -2.60857853e-05]]
Почти собственное число  2.8396503662887658
Невязка  0.9022675


Результат итерации 2-[[ 6.58420655e-06 -8.52195679e-06  3.43869823e-05 ...  2.57496449e-07
  -5.33909411e-06 -2.44849577e-05]]
Почти собственное число  11882471595.04386
Невязка  0.87114446


Результат итерации 3-[[ 6.55260398e-06 -8.48104883e-06  3.42219546e-05 ...  2.56260556e-07
  -5.31346674e-06 -2.43674370e-05]]
Почти собственное число  11932619023.493448
Невязка  0.83991726


Результат итерации 4-[[ 6.52456234e-06 -8.44474915e-06  3.40755273e-05 ...  2.55163927e-07
  -5.29072676e-06 -2.42631586e-05]]
Почти собственное число  11961400149.022196
Невязка  0.80807946


Результат итерации 5-[[ 6.48890811e-06 -8.39859643e-06  3.38893423e-05 ...  2.537695

Невязка  0.00364166


Результат итерации 86-[[ 3.74892463e-06 -4.85212477e-06  1.95798502e-05 ...  1.46614346e-07
  -3.03995433e-06 -1.39413054e-05]]
Почти собственное число  12453795072.594408
Невязка  0.00339386


Результат итерации 87-[[ 3.74767400e-06 -4.85050605e-06  1.95733186e-05 ...  1.46565436e-07
  -3.03894020e-06 -1.39366546e-05]]
Почти собственное число  12453796550.062809
Невязка  0.00316292


Результат итерации 88-[[ 3.74650829e-06 -4.84899725e-06  1.95672306e-05 ...  1.46519847e-07
  -3.03799492e-06 -1.39323196e-05]]
Почти собственное число  12453797833.300276
Невязка  0.00294769


Результат итерации 89-[[ 3.74542174e-06 -4.84759091e-06  1.95615561e-05 ...  1.46477355e-07
  -3.03711385e-06 -1.39282790e-05]]
Почти собственное число  12453798947.84027
Невязка  0.00274711


Результат итерации 90-[[ 3.74440900e-06 -4.84628009e-06  1.95562670e-05 ...  1.46437748e-07
  -3.03629261e-06 -1.39245129e-05]]
Почти собственное число  12453799915.85972
Невязка  0.00256017


Результат 

In [73]:
##### Проверяем, какое из корней найденного числа подходит в качестве собственного для просто обратной матрицы.
##### В данном примере получаем, что для отрицательного
La = np.sqrt(L_prev)
h_1 = d_inv*h - (u.T@(d_inv*h))*(d_inv*u)/mu
print(LA.norm((h_1 - La*h)))
print(LA.norm((h_1 + La*h)))

print(La)

1.7581350077908427e-09
223193.2464142136
111596.62320710674


In [74]:
##### Проверяем, какое из корней найденного числа подходит в качестве собственного для просто обратной матрицы.
##### В данном примере получаем, что для отрицательного
La = np.sqrt(L_prev)
h_1 = d_inv*h - (u.T@(d_inv*h))*(d_inv*u)/mu
print(LA.norm((h_1 - La*h)))
print(LA.norm((h_1 + La*h)))

print(La)

1.7581350077908427e-09
223193.2464142136
111596.62320710674


In [75]:
###### Собственное число матрицы А
print(h.T@(d*h) + (h.T@u)**2)

[[8.96084461e-06]]
