# 1) n = 100

In [1]:
import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt

In [2]:
n = 100
u = np.random.normal(0,1,n)
d = np.random.normal(0,1,n)

In [3]:
u @ u.T # Хотим получить матрицу, а не число !!!

106.42946059868154

In [4]:
u = u[:, np.newaxis] # Делаем из u - вектор столбец. Чтобы посчитать u @ u.T (должна получиться матрица, а не число)

In [5]:
u.shape

(100, 1)

In [6]:
# Cоберем матрицу А
A = (u @ u.T)/(u.T @ u) + np.diag(d)
np.min(LA.eigvalsh(A)) # минимальное собственное число

-1.7385167842136224

In [7]:
sys = LA.eigh(A)
sys[0]

array([-1.73851678, -1.62644548, -1.56829465, -1.56273698, -1.53375335,
       -1.50741079, -1.50425458, -1.39420095, -1.38937896, -1.38061532,
       -1.07765751, -0.98073215, -0.94698553, -0.87285508, -0.83162167,
       -0.78728564, -0.76311191, -0.74655765, -0.72642373, -0.7104558 ,
       -0.69477001, -0.63227305, -0.62251765, -0.59675518, -0.54437278,
       -0.50801861, -0.48333293, -0.48212882, -0.47693963, -0.4737236 ,
       -0.45487307, -0.44116644, -0.41150389, -0.32843265, -0.31330652,
       -0.27541373, -0.27054996, -0.25752395, -0.22070897, -0.20437378,
       -0.16149847, -0.15398327, -0.12167768, -0.11457703, -0.07502704,
       -0.05243305, -0.03710919, -0.01099462, -0.00417338,  0.02318   ,
        0.03940779,  0.09404535,  0.12366731,  0.13338433,  0.14578563,
        0.15018259,  0.17762247,  0.20650521,  0.21040274,  0.21807942,
        0.22658964,  0.23177144,  0.2648968 ,  0.29443826,  0.30009458,
        0.30187752,  0.30692544,  0.31573344,  0.33882026,  0.34

In [8]:
sys[1]

array([[-1.33983588e-03,  9.55043039e-04, -1.24367681e-03, ...,
         4.24170064e-03, -6.75433448e-04,  5.45757375e-03],
       [-8.68999578e-05,  6.23164651e-05, -8.14272737e-05, ...,
         2.22963334e-04, -3.59956129e-05,  2.91386734e-04],
       [ 7.18065078e-03, -1.43490109e-02, -9.94833383e-01, ...,
        -8.71241828e-04,  1.49064464e-04, -1.21654201e-03],
       ...,
       [ 7.84582891e-04, -5.96708495e-04,  8.07599627e-04, ...,
        -7.20320757e-04,  1.20886864e-04, -9.83856686e-04],
       [ 2.99289819e-03, -2.26442144e-03,  3.05479822e-03, ...,
        -2.90850502e-03,  4.87487797e-04, -3.96677288e-03],
       [-6.09096157e-04,  4.29428028e-04, -5.55782748e-04, ...,
         3.38589024e-03, -5.11303694e-04,  4.10310989e-03]])

In [10]:
a = sys[:][:][1]
c =a[:][0]
c # собственный вектор, соответствующий минимальному собственному занчению

array([-1.33983588e-03,  9.55043039e-04, -1.24367681e-03,  3.66099463e-04,
       -3.37317390e-03,  2.14795617e-03, -1.53260330e-03,  8.78026202e-04,
       -4.50407951e-04,  2.72518122e-03, -2.83030642e-03,  1.26076518e-02,
       -1.11208772e-02,  1.06479612e-03, -9.38391776e-04, -1.12882576e-03,
       -6.12837241e-03,  2.35412498e-03,  1.21194745e-04,  3.32230660e-04,
       -8.64062995e-03, -9.75766190e-05, -1.65883251e-03,  8.26451299e-03,
        4.70605283e-03, -4.73383339e-03, -7.50015272e-04, -3.72540530e-03,
       -3.43333651e-03, -2.96159839e-03,  9.55377794e-03,  2.15889359e-03,
        3.35960141e-03, -2.16053931e-03, -1.24702467e-02,  2.89910974e-03,
        4.37856564e-03,  4.47317699e-03,  2.08921139e-03,  7.58807030e-03,
       -3.80881619e-03, -8.35411924e-03, -1.19296331e-02, -2.83604753e-03,
        1.42884326e-03,  3.71033299e-03,  1.93384252e-02, -4.93969913e-04,
       -1.06349864e-02, -3.12600135e-02, -3.77787146e-02,  7.57199430e-03,
        2.07654506e-02,  