In [516]:
import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt

In [517]:
A = np.array([[3,1,0,0],[1,2,0,1],[0,0,1,1],[0,1,1,1]])

In [518]:
# 1) Степенная итерация

v = np.random.random(4) # Cтартуем с случайного вектора
v/=LA.norm(v) # Нормировка случайного вектора

In [519]:
v

array([0.57569053, 0.56619966, 0.15827069, 0.5682858 ])

In [520]:
for i in range(10): # Цикл для поиска максимального собств. знач.
    v = A @ v
    v/=LA.norm(v)

In [521]:
v # вектор, который получился после того,как на изначальный вектор подействовали матрицей А 10 раз (собственный вектор)

array([0.77100501, 0.58102115, 0.0897077 , 0.24478201])

In [522]:
(A @ v)/v # Максимальное собственное значение для получившегося после цикла собственного вектора

array([3.75358934, 3.7482789 , 3.72866212, 3.74010679])

In [523]:
# Найдем какое кол-во шагов нужно, чтобы получить настоящий собственный вектор с точностью 10**(-3)

sys = LA.eigh(A) # найдем настоящие собственные числа и вектора

In [524]:
sys[0] # Собственные значения (максимальное примерно совпадает с тем, которе мы посчитали степенной итерацией)

array([-0.28399787,  1.21473855,  2.3184589 ,  3.75080042])

In [525]:
sys[1] # Матрица собственных векторов (по столбцам). Максимальному собствен. знач. соотв. последний столбец

array([[-0.11203111,  0.35688275,  0.51313991, -0.77250966],
       [ 0.36790993, -0.63712901, -0.34972594, -0.58000058],
       [ 0.56719284,  0.66792899, -0.4736691 , -0.08832178],
       [-0.7282744 ,  0.1434301 , -0.62451324, -0.2429556 ]])

In [526]:
psi = sys[1][:,-1] # Вытащили и запомнили последний стоблец матрицы собственных значений (истинный соб. вектор)

In [527]:
# Перед тем как считать разность v и psi, надо их выравнять по знаку первого элемента
# Так как с.в определен с точность до знака (коэффициента)

v *= np.sign(v[0]/psi[0])

In [528]:
# Теперь у v и psi одинаковые знаки
print(v)
print(psi)

[-0.77100501 -0.58102115 -0.0897077  -0.24478201]
[-0.77250966 -0.58000058 -0.08832178 -0.2429556 ]


In [529]:
LA.norm(v - psi) # Это именно та норма, которая нам нужна (см. np.info(LA.norm))

0.0029261092129212424

In [530]:
# Посмторим как меняется невязка в цикле:
v = np.random.random(4)
v/=LA.norm(v)
for i in range(15): # Цикл для поиска максимального собств. знач.
    v = A @ v
    v/=LA.norm(v)
    v *= np.sign(v[0]/psi[0])
    print('Номер итерации' + f'{i}',LA.norm(v - psi))

Номер итерации0 0.410898562544595
Номер итерации1 0.22523901731587792
Номер итерации2 0.13309224625959534
Номер итерации3 0.0812152238981829
Номер итерации4 0.05003808687158664
Номер итерации5 0.030906796324653363
Номер итерации6 0.019101506177209265
Номер итерации7 0.011806913661545152
Номер итерации8 0.007298169531406209
Номер итерации9 0.004511193767893307
Номер итерации10 0.002788483482805386
Номер итерации11 0.0017236300497317785
Номер итерации12 0.0010654172715092644
Номер итерации13 0.0006585598853082438
Номер итерации14 0.00040707155506268733


In [531]:
# Видим, что на 13 итерации невязка становится порядка 10**(-3)

In [532]:
# 2) Обратная итерация с mu = 3.5

v = np.random.random(4)
v/=LA.norm(v)
mu = 3.5
B = LA.inv(A - mu * np.eye(4))
sys = LA.eigh(A)
psi = sys[1][:,-1]
for i in range(15): # Цикл для поиска собств. знач. около mu
    v = B @ v
    v/=LA.norm(v)
    v *= np.sign(v[0]/psi[0])
    print('Номер итерации' + f'{i}',LA.norm(v - psi))

Номер итерации0 0.10290407329258318
Номер итерации1 0.015827746485905788
Номер итерации2 0.002962483274057791
Номер итерации3 0.0006052366221191453
Номер итерации4 0.00012711826196697953
Номер итерации5 2.6905965267562377e-05
Номер итерации6 5.706847962568125e-06
Номер итерации7 1.2111196171405908e-06
Номер итерации8 2.570648865078946e-07
Номер итерации9 5.4565212107101156e-08
Номер итерации10 1.158226744774743e-08
Номер итерации11 2.4585131358695633e-09
Номер итерации12 5.218576287492196e-10
Номер итерации13 1.107722150444186e-10
Номер итерации14 2.3513228857696902e-11


In [533]:
# Видим, что невязка на 3 итерации становится порядка 10**(-3)

In [534]:
v # Примерно собств. вектор

array([-0.77250966, -0.58000058, -0.08832178, -0.2429556 ])

In [535]:
(A @ v)/v

array([3.75080042, 3.75080042, 3.75080042, 3.75080042])

In [536]:
# 3) Обратная итерация с mu = 3.7

v = np.random.random(4)
v/=LA.norm(v)
mu = 3.7
B = LA.inv(A - mu * np.eye(4))
sys = LA.eigh(A)
psi = sys[1][:,-1]
for i in range(15): # Цикл для поиска собств. знач. около mu
    v = B @ v
    v/=LA.norm(v)
    v *= np.sign(v[0]/psi[0])
    print('Номер итерации' + f'{i}',LA.norm(v - psi))

Номер итерации0 0.0150908695558879
Номер итерации1 0.00037654205888353916
Номер итерации2 1.1411852716678726e-05
Номер итерации3 3.8947752195394034e-07
Номер итерации4 1.396861800819143e-08
Номер итерации5 5.095957289894016e-10
Номер итерации6 1.8692349370838725e-11
Номер итерации7 6.866633395230303e-13
Номер итерации8 2.5354855051481836e-14
Номер итерации9 7.874956775073054e-16
Номер итерации10 2.0955000055363631e-16
Номер итерации11 1.6243534171511178e-16
Номер итерации12 1.3092278833360675e-16
Номер итерации13 1.3092278833360675e-16
Номер итерации14 1.3092278833360675e-16


In [513]:
# Видим, что невязка на 1 итерации становится порядка 10**(-3)
# Так и должно быть : невзка при mu = 3.7 сходится быстрее к 0, чем при  mu = 3.5 (так как знаем, что макс с.в = 3.75...)