In [2]:
import numpy as np
import matplotlib.pyplot as plt

# ВЫвод матрицы смотри на отдельном листке
A = np.array([[0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5], [1,1,1,1,1,1,1,1,1,1]])
u, s, vh = np.linalg.svd(A)

In [5]:
np.diag(s)

array([[18.44109698,  0.        ],
       [ 0.        ,  1.55754364]])

In [6]:
a = np.array([[1],[0]])

In [22]:
sigma_pinv = np.zeros((10,2))
sigma_pinv[0,0] = 1/s[0]
sigma_pinv[1,1] = 1/s[1]
print(sigma_pinv)

[[0.05422671 0.        ]
 [0.         0.64203659]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]


In [19]:
f_min1 = vh.T @ sigma_pinv @ u.T @ a
print(len(f_min1))
f_min1

10


array([[-0.05454545],
       [-0.04242424],
       [-0.03030303],
       [-0.01818182],
       [-0.00606061],
       [ 0.00606061],
       [ 0.01818182],
       [ 0.03030303],
       [ 0.04242424],
       [ 0.05454545]])

In [20]:
# Проверка с помощью псевдоинверса

A_pinv = np.linalg.pinv(A)
f_min2 = A_pinv @ a
print(len(f_min2))
f_min2

10


array([[-0.05454545],
       [-0.04242424],
       [-0.03030303],
       [-0.01818182],
       [-0.00606061],
       [ 0.00606061],
       [ 0.01818182],
       [ 0.03030303],
       [ 0.04242424],
       [ 0.05454545]])

In [21]:
# Как и ожидалось ответ совпал