In [15]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
a = np.array([[1,0],[0,1],[1,0]])

In [17]:
q, r = np.linalg.qr(a)

In [18]:
q

array([[-0.70710678,  0.        ],
       [-0.        ,  1.        ],
       [-0.70710678, -0.        ]])

In [19]:
r

array([[-1.41421356,  0.        ],
       [ 0.        ,  1.        ]])

In [20]:
q@r

array([[1., 0.],
       [0., 1.],
       [1., 0.]])

In [22]:
q@(q.T.conj())

array([[0.5, 0. , 0.5],
       [0. , 1. , 0. ],
       [0.5, 0. , 0.5]])

In [24]:
q.T

array([[-0.70710678, -0.        , -0.70710678],
       [ 0.        ,  1.        , -0.        ]])