In [1]:
# 1) Напишем функцию, которая напрямую вычисляет обратную матрицу от суммы:

import numpy as np
def woodbury(A,U,V):
    return np.linalg.inv(A + U@V)

In [6]:
# 2) Теперь напишем, функцию вычисляющую обратную матрицу от суммы по формуле (1):

import numpy as np
def fastwoodbury1(A,U,V,k):
    A_inv = np.diag(1./np.diag(A)) # Бстрое обращение диагональной матрицы (А - диоганальна по условию)
    B_inv = np.linalg.inv(np.eye(k) + V @ A_inv @ U)
    return A_inv - A_inv @ U @ B_inv @ V @ A_inv

In [7]:
# A - диагональная матрица p*p, U - p*k, V - k*p
A_inv_diag = np.array([1, 2, 3, 4, 5])
A1 = A_inv_diag.reshape(-1,1)
A1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
U =np.array([6,7,8,9,10,11,12,13,14,15])
U1 = U.reshape(5,2)
U1

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [9]:
A1 * U1

array([[ 6,  7],
       [16, 18],
       [30, 33],
       [48, 52],
       [70, 75]])

In [10]:
np.diag(A_inv_diag) @ U1

array([[ 6,  7],
       [16, 18],
       [30, 33],
       [48, 52],
       [70, 75]])

In [11]:
# Вывод np.diag(A_inv_diag) @ U1 тоже самое, что A1 * U1 (только * - быстрее)
# Значит можем улучшить наш код (fastwoodbury2 быстрее чем fastwoodbury1)

import numpy as np
def fastwoodbury2(A,U,V,k):
    A_inv_diag = 1./np.diag(A) # Это вектор
    B_inv = np.linalg.inv(np.eye(k) + (V * A_inv_diag) @ U)
    return np.diag(A_inv_diag) - (A_inv_diag.reshape(-1,1) * U @ B_inv @ V * A_inv_diag)

In [14]:
# Рассмотрим конкретный случай 
# 1) Быстрая функция
p = 5000
k = 100
A = np.diag(np.random.randn(p))
U = np.random.randn(p, k)
V = np.random.randn(k, p)
fastwoodbury2(A,U,V,k)

array([[-7.03684669e-01, -1.00178610e-04, -3.40659351e-03, ...,
         9.55361446e-03, -1.80703153e-03, -5.27861874e-03],
       [-6.56185091e-03, -9.29678790e-01,  4.57643951e-03, ...,
         1.02849369e-02, -1.35815513e-04,  2.87653253e-02],
       [ 1.13097891e-02,  2.54717262e-03,  6.58460600e-01, ...,
        -9.32778396e-03, -6.94009632e-03, -5.01272411e-02],
       ...,
       [ 1.45372673e-04,  2.44318919e-04, -8.52848440e-04, ...,
         1.13089616e+00,  2.55061752e-03,  4.47748464e-02],
       [ 1.68123525e-02, -4.75304836e-03,  1.57408761e-03, ...,
         2.78477048e-03,  1.04936930e+00,  6.20915859e-02],
       [-3.38968717e-02,  3.97703124e-02,  1.41714490e-02, ...,
         4.21128976e-02,  1.05012024e-01, -4.56547858e+00]])

In [16]:
# 2) Медленная функция

p = 5000
k = 100
A = np.diag(np.random.randn(p))
U = np.random.randn(p, k)
V = np.random.randn(k, p)
woodbury(A,U,V)

array([[-1.71491109e+00, -1.60625064e+00,  1.47401590e-02, ...,
        -3.96658160e-01, -2.58652214e-01,  8.36132359e-02],
       [-3.13306638e-01, -2.64646357e+00, -9.93124422e-03, ...,
         3.29064775e-01,  2.71925317e-01, -8.25245722e-02],
       [ 3.14370450e-01, -1.23014942e+00,  7.97093291e-01, ...,
        -2.66480993e-01, -1.64606272e-01,  6.20222997e-02],
       ...,
       [-3.94779813e-02,  9.08842757e-03,  2.92147472e-03, ...,
        -1.34678427e+00,  7.84026813e-05,  3.06329794e-03],
       [-1.15514619e-01,  4.02624105e-01, -4.75873847e-05, ...,
         8.25819727e-02, -7.43094141e-01, -1.68093063e-02],
       [ 6.09793014e-02, -2.24021529e-01,  4.06550260e-03, ...,
        -5.87507450e-02, -3.18922428e-02, -7.63612857e-01]])

In [ ]:
# fastwoodbury(1,2) быстрее потому что, уменьшили кол-во операций (нам легче обращать матрицу k*k, чем p*p (p>k))